'use client'

import './globals.css'
import { Inter } from 'next/font/google'
import { ThemeProvider } from 'styled-components'
import StyledJsxRegistry from './registry'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
const light = {
  colors: {
    primary: 'rgb(44,177,188)',
    secondary: 'rgba(44,177,188,0.8)',
    grey: 'rgb(72,101,129)',
  },
  borderRadius: '2px',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <ThemeProvider theme={light}>
            {children}
          </ThemeProvider>
        </StyledJsxRegistry>
      </body>
    </html>
  )
}
